### ISSUE TITLE
"InvalidArgument: Your request contains one or more invalid invalidation paths" - During next-tf-deploy lambda execution

### ISSUE THREAD

**Issue by jonathanabila** [dealmore/terraform-aws-next-js#169]
Hi folks!

Amazing work done here!! :rocket:

I'm using this amazing implementation to deploy my application, and I'm getting this error on the `next-tf-deploy` lambda: 

```
2021-08-18T14:35:09.095Z	ba33556c-a3ad-4854-92d5-b33dde0261a3	INFO	InvalidArgument: Your request contains one or more invalid invalidation paths.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_xml.js:53:29)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) {
  code: 'InvalidArgument',
  time: 2021-08-18T14:35:09.092Z,
  requestId: '54132846-8f00-4b96-b0dd-cbbcf9782239',
  statusCode: 400,
  retryable: false,
  retryDelay: 78.49245719486876
}
```

My current implementation is this one:

```terraform
module "tf_next" {
  source = "dealmore/next-js/aws"
  version = "v0.9.1"

  use_awscli_for_static_upload = true

  deployment_name = var.deployment_name

  create_image_optimization = false

  # Prevent creation of the main CloudFront distribution
  cloudfront_create_distribution = false
  cloudfront_external_id         = aws_cloudfront_distribution.distribution.id
  cloudfront_external_arn        = aws_cloudfront_distribution.distribution.arn

  providers = {
    aws.global_region = aws.global_region
  }

  tags = var.tags
}
```

I think it's worth mentioning that I had to reimplement the cloudfront distribution to change cloudfront aliases - maybe I'm doing something wrong, but it would be awesome to be able to do that without all that complexity and duplicated code.

Do you have any idea why I'm getting this error? Any ideas?

Thanks for all the hard work :rocket: :rocket: :rocket:

**Comment by ofhouse** [comment]
Hi,

this looks like a bug, since the AWS API is not accepting the invalidation paths that are sent to the CloudFront distribution.
We have routines in place that validate the invalidation paths before they are sent to the CloudFront distribution.

Unfortunately it's very difficult to debug since the full request is not logged.
Are you able to reproduce the bug with different deployments?

**Comment by jonathanabila** [comment]
> Hi,
> 
> this looks like a bug, since the AWS API is not accepting the invalidation paths that are sent to the CloudFront distribution.
> We have routines in place that validate the invalidation paths before they are sent to the CloudFront distribution.
> 
> Unfortunately it's very difficult to debug since the full request is not logged.
> Are you able to reproduce the bug with different deployments?

Can the deployment be a different workspace? Or do you mean different projects?

**Comment by ofhouse** [comment]
Not sure what a workspace is in this context.

What I mean is: After the initial `tf-next build` and `terraform apply` (first deployment) when you then make changes to your Next.js project (e.g. add remove something inside a file) and then update the existing deployment with `tf-next build` & `terraform apply` (second deployment).

Is the error raised on the first or the second deployment?
And when you create more deployments (3rd, 4th, etc.) is the error still present there (Is the error raised in each following deployment)?

**Comment by jonathanabila** [comment]
> Is the error raised on the first or the second deployment?

Yes - I did at least 10 deployments, all gave the same error - no invalidations were generated.

Yesterday I had to create a new terraform environment and everything worked as expected - I didn't change anything: confused:

On Monday, I will delete the environment with the problem and test if I still have the same error when redeploying everything.

**Comment by jonathanabila** [comment]
I haven't changed anything and now everything is working as expected - I have no idea why, but it's resolved. Thanks for your help @ofhouse :)
