### ISSUE TITLE
NEXT_NO_ROUTES_MANIFEST error during `npm run tf-next`

### ISSUE THREAD

**Issue by derjust** [dealmore/terraform-aws-next-js#53]
I tried following the setup guide but my build failed:

`package.json` excerpts:
```json
{
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "tf-next": "tf-next build"
  },
...
  "dependencies": {
    "next": "^10.0.6",
    "react": "17.0.1",
  }
...
}
```

Running `$ npm run tf-next` produces this output:
```
> my-app@0.1.0 tf-next /Users/sebastian/development/app
> tf-next build

Installing dependencies...
yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 12.19s.
Running "yarn run build"
yarn run v1.22.4
$ next build
Loaded env from /private/var/folders/k0/41_ltq_d1v571z67g9bjb2h00000gn/T/tmp-75327-inHXi38AbvJA/.env.local
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (6/6)
info  - Finalizing page optimization

Page                                Size     First Load JS
┌ ○ /                               806 B          68.4 kB
├   /_app                           0 B            62.7 kB
├ ○ /404                            2.77 kB        65.5 kB
├ λ /api/s3-upload-token            0 B            62.7 kB
├ ○ /checkout                   5.18 kB        72.8 kB
├ ○ /reading                    95 kB           163 kB
├   └ css/4f6d1999152a411e8da4.css  135 B
└ ○ /review                     1.47 kB        69.1 kB
+ First Load JS shared by all       62.7 kB
  ├ chunks/commons.2ac29a.js        13.3 kB
  ├ chunks/framework.9d5241.js      41.8 kB
  ├ chunks/main.3ff250.js           6.32 kB
  ├ chunks/pages/_app.ce9584.js     545 B
  ├ chunks/webpack.50bee0.js        751 B
  └ css/a0d15b181925e64a7258.css    2.7 kB

λ  (Lambda)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

✨  Done in 20.38s.
Build failed:
NowBuildError: A "routes-manifest.json" couldn't be found. This is normally caused by a misconfiguration in your project.
Please check the following, and reach out to support if you cannot resolve the problem:
  1. If present, be sure your `build` script in "package.json" calls `next build`.  2. Navigate to your project's settings in the Vercel dashboard, and verify that the "Build Command" is not overridden, or that it calls `next build`.  3. Navigate to your project's settings in the Vercel dashboard, and verify that the "Output Directory" is not overridden. Note that `next export` does **not** require you change this setting, even if you customize the `next export` output directory.
    at Object.getRoutesManifest (/Users/sebastian/development/app/node_modules/@dealmore/next-tf/dist/index.js:37244:15)
    at async Object.build (/Users/sebastian/development/app/node_modules/@dealmore/next-tf/dist/index.js:35211:28)
    at async Object.buildCommand [as default] (/Users/sebastian/development/app/node_modules/tf-next/dist/commands/build.js:121:29) {
  hideStackTrace: true,
  code: 'NEXT_NO_ROUTES_MANIFEST',
  link: 'https://err.sh/vercel/vercel/now-next-routes-manifest',
  action: undefined
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.1.0 tf-next: `tf-next build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.1.0 tf-next script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sebastian/.npm/_logs/2021-02-14T00_24_15_009Z-debug.log
```

Other local versions:
```
$ npm -v
6.14.5
$ node -v
v12.18.1
```

**Comment by derjust** [comment]
Figured it out:

I had  in my `next.config.js`:
```json
module.exports = {
  distDir: 'build',
  }
```
removing the `destDir` solved the issue and the build completes:
```
...
✨  Done in 22.20s.
Traced Next.js serverless functions for external files in: 1745.201ms
Compressed shared serverless function files: 1385.656ms
All serverless functions created in: 73.771ms
409352 total bytes
Build successful!
```
